//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onliner.Model.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=e24bafa8-2d95-4c3b-8677-a2bb00a52dce.sqlserver.sequelizer.com;Database=dbe" +
            "24bafa82d954c3b8677a2bb00a52dce;User ID=pifzisandswcunoi;Password=G4Czh4JAq7hBAG" +
            "V5mWRoQmPUAi6FgWyinNxP884PRUNuJGdH653aVsMunQ877duB;")]
        public string onlinerConnectionString {
            get {
                return ((string)(this["onlinerConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=e24bafa8-2d95-4c3b-8677-a2bb00a52dce.sqlserver.sequelizer.com;Persist" +
            " Security Info=True;User ID=pifzisandswcunoi;Password=G4Czh4JAq7hBAGV5mWRoQmPUAi" +
            "6FgWyinNxP884PRUNuJGdH653aVsMunQ877duB")]
        public string DataSourceConnectionString {
            get {
                return ((string)(this["DataSourceConnectionString"]));
            }
        }
    }
}
