//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onliner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Onliner.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onliner Hub.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading article....
        /// </summary>
        public static string ArticleLoadingMsg {
            get {
                return ResourceManager.GetString("ArticleLoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load simplified content from Readability. Article description would be used instead. Check your internet connection!.
        /// </summary>
        public static string ArticleRetrieveError {
            get {
                return ResourceManager.GetString("ArticleRetrieveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO ONLINER.BY.
        /// </summary>
        public static string AutoSectionTitle {
            get {
                return ResourceManager.GetString("AutoSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all data from local storage.
        /// </summary>
        public static string ClearCacheTitle {
            get {
                return ResourceManager.GetString("ClearCacheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading comments....
        /// </summary>
        public static string CommentLoadingMsg {
            get {
                return ResourceManager.GetString("CommentLoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CommentsMenuText {
            get {
                return ResourceManager.GetString("CommentsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not store read articles locally.
        /// </summary>
        public static string DeleteReadArticlesTitle {
            get {
                return ResourceManager.GetString("DeleteReadArticlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading articles....
        /// </summary>
        public static string FeedLoadingMsg {
            get {
                return ResourceManager.GetString("FeedLoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use minimal style for feed list.
        /// </summary>
        public static string FeedStyleTitle {
            get {
                return ResourceManager.GetString("FeedStyleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access www.onliner.by to retrieve new articles. Check your internet connection!.
        /// </summary>
        public static string FeedUpdateError {
            get {
                return ResourceManager.GetString("FeedUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font family.
        /// </summary>
        public static string FontFamilyTitle {
            get {
                return ResourceManager.GetString("FontFamilyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string FontSizeTitle {
            get {
                return ResourceManager.GetString("FontSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.onliner.by.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark article read when opened.
        /// </summary>
        public static string MarkReadWhenOpenTitle {
            get {
                return ResourceManager.GetString("MarkReadWhenOpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEOPLE ONLINER.BY.
        /// </summary>
        public static string PeopleSectionTitle {
            get {
                return ResourceManager.GetString("PeopleSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REALT ONLINER.BY.
        /// </summary>
        public static string RealtSectionTitle {
            get {
                return ResourceManager.GetString("RealtSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshMenuText {
            get {
                return ResourceManager.GetString("RefreshMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storage.
        /// </summary>
        public static string StorageBlockTitle {
            get {
                return ResourceManager.GetString("StorageBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscriptions.
        /// </summary>
        public static string SubscriptionsBlockTitle {
            get {
                return ResourceManager.GetString("SubscriptionsBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TECHNOLOGIES ONLINER.BY.
        /// </summary>
        public static string TechSectionTitle {
            get {
                return ResourceManager.GetString("TechSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view style.
        /// </summary>
        public static string ViewSettingsBlockTitle {
            get {
                return ResourceManager.GetString("ViewSettingsBlockTitle", resourceCulture);
            }
        }
    }
}
